name: msw_dio_interceptor
description: A powerful mock interceptor for Dio, inspired by MSW. Easily mock HTTP requests in your Dart and Flutter applications.
version: 1.0.0
repository: https://github.com/johnnydev-tech/msw_dio_interceptor
homepage: https://github.com/johnnydev-tech/msw_dio_interceptor


environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  dio: ^5.4.3+1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.9
  fake_async: ^1.3.1
